---
projects:
  - file: octokeyz.kicad_pro
    pcb-render:
      enable: true
      include-dnp: true
      width: 3620
      height: 1840
      zoom: 1.8
      # pan:
      #   y: 0.8
      scales:
        - 480
        - 720
        - 1080
      sides:
        - top
        - bottom
    pcb-ibom:
      enable: true
    pcb-gerber:
      enable: true
      copy-pattern: gerber/*.zip
    sch-export-pdf:
      enable: true
